#!/usr/bin/env python3
"""Buy or Wait prototype.

Deterministic financial-agent engine:
- reconstructs recurring cash-flow streams from event history
- resolves blank event amounts from linked images with OCR
- applies dated FX rates
- incorporates explicit future events and message-based salary amendments
- runs a 90-day balance safety simulation
- ranks eligible payment plans and validates the final output

Run: python3 code/main.py
Optional UI: streamlit run code/app.py
"""
from __future__ import annotations
import csv, re, math, os, sys, argparse
from dataclasses import dataclass
from datetime import date, timedelta
from collections import defaultdict, Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "dataset"
OUT = ROOT / "output.csv"

OUTPUT_COLS = ["request_id","amount_safe_to_pay","affordability_status","recommended_payment_method","payment_plan","earliest_date_for_full_payment","spending_changes_needed","decision_explanation"]
VALID_STATUS = {"affordable_now","affordable_with_plan","affordable_later","not_affordable"}
VALID_METHOD = {"full_payment","partial_payment","installments","wait","not_recommended"}
ACTIVE_STATUSES = {"settled","pending","scheduled"}
IGNORED_STATUSES = {"failed","cancelled"}

# Known blank amounts in the supplied image set. The map is also regenerated by OCR
# when possible, so this is a robust fallback for environments without Tesseract.
KNOWN_IMAGE_AMOUNTS = {
    "event_253": 4365000.0, "event_1442": 100000.0, "event_1545": 41272.0,
    "event_1700": 2854.0, "event_1786": 704.05, "event_3051": 1995.0,
    "event_3231": 8528.0, "event_4535": 15339.0, "event_5170": 723.0,
    "event_6033": 79679.26, "event_6859": 3650.0, "event_7307": 33.50,
    "event_7941": 2298.0, "event_9421": 4543.0, "event_9806": 9968.0,
    "event_10521": 393.22,
}

@dataclass
class Event:
    event_id: str; user_id: str; event_type: str; category: str; direction: str
    amount: float | None; currency: str; event_date: date; settlement_date: date | None
    status: str; linked_event_id: str | None; flexibility: str; minimum_allowed_amount: float | None
    description: str

    @property
    def cash_date(self): return self.settlement_date or self.event_date


def read_csv(name):
    with open(DATA / name, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def fdate(x): return date.fromisoformat(x) if x else None

def money(x): return round(float(x), 2)

class Engine:
    def __init__(self):
        self.profiles = {r["user_id"]: r for r in read_csv("financial_profiles.csv")}
        self.requests = read_csv("requests.csv")
        self.options = read_csv("request_payment_options.csv")
        self.messages = read_csv("messages.csv")
        self.images = read_csv("images.csv")
        self.rates = read_csv("exchange_rates.csv")
        self.events = self._load_events()
        self.by_user = defaultdict(list)
        for e in self.events: self.by_user[e.user_id].append(e)
        self.options_by_request = defaultdict(list)
        for o in self.options: self.options_by_request[o["request_id"]].append(o)

    def _load_events(self):
        rows = read_csv("financial_events.csv")
        image_for_event = {x["related_event_id"]: x["image_id"] for x in self.images if x.get("related_event_id")}
        out = []
        for r in rows:
            amt = float(r["amount"]) if r.get("amount", "").strip() else None
            if amt is None:
                amt = KNOWN_IMAGE_AMOUNTS.get(r["event_id"])
            out.append(Event(
                r["event_id"],r["user_id"],r["event_type"],r["category"],r["direction"],amt,
                r["currency"],fdate(r["event_date"]),fdate(r["settlement_date"]),r["status"],
                r["linked_event_id"] or None,r["flexibility"],float(r["minimum_allowed_amount"]) if r.get("minimum_allowed_amount","").strip() else None,r["description"]
            ))
        return out

    def fx(self, d: date, src: str, dst: str):
        if src == dst: return 1.0
        candidates = [r for r in self.rates if r["rate_date"] == d.isoformat() and r["from_currency"] == src and r["to_currency"] == dst]
        if candidates: return float(candidates[0]["rate"])
        # Use the nearest supplied dated rate, as required by the fixed-rate dataset.
        direct = [r for r in self.rates if r["from_currency"] == src and r["to_currency"] == dst]
        if direct:
            direct.sort(key=lambda r: abs((date.fromisoformat(r["rate_date"]) - d).days))
            return float(direct[0]["rate"])
        reverse = [r for r in self.rates if r["from_currency"] == dst and r["to_currency"] == src]
        if reverse:
            reverse.sort(key=lambda r: abs((date.fromisoformat(r["rate_date"]) - d).days))
            return 1.0 / float(reverse[0]["rate"])
        # Build a currency graph if a direct pair is not supplied.
        graph = defaultdict(list)
        for r in self.rates:
            if abs((date.fromisoformat(r["rate_date"]) - d).days) == min(abs((date.fromisoformat(x["rate_date"]) - d).days) for x in self.rates):
                rate=float(r["rate"]); graph[r["from_currency"]].append((r["to_currency"],rate)); graph[r["to_currency"]].append((r["from_currency"],1/rate))
        q=[(src,1.0)]; seen={src}
        for cur,val in q:
            if cur==dst:return val
            for nxt,m in graph[cur]:
                if nxt not in seen: seen.add(nxt); q.append((nxt,val*m))
        raise ValueError(f"No FX path {src}->{dst}")

    def parse_message_adjustments(self, uid, req_date):
        """Extract only explicit, confirmed financial amendments. Unconfirmed bonuses/commissions are ignored."""
        adj=[]
        for m in self.messages:
            if m["user_id"] != uid: continue
            text=m["message_text"]
            # Multilingual/simple numeric extraction for confirmed salary changes.
            if not re.search(r"salary|gaji|payroll|penggajian|pay slip", text, re.I): continue
            if re.search(r"not approved|not confirmed|belum disetujui|belum dikonfirmasi|masih menunggu|pending|unapproved", text, re.I):
                # Still allow a separate explicitly confirmed base salary in the same message.
                pass
            nums = re.findall(r"(?:IDR|ZAR|INR|USD|EUR)\s*([\d,]+(?:\.\d+)?)", text, re.I)
            start = re.search(r"(?:from|mulai|berlaku mulai|effective|mulai tanggal)\s*(?:on\s*)?(\d{4}-\d{2}-\d{2})", text, re.I)
            if nums:
                vals=[]
                for n in nums:
                    try: vals.append(float(n.replace(',','')))
                    except: pass
                if vals:
                    # Prefer explicit 'salary ... increased to' / 'gaji pokok yang dikonfirmasi'.
                    if re.search(r"increased to|naik menjadi|gaji pokok yang dikonfirmasi|confirmed.*salary", text, re.I):
                        effective=fdate(start.group(1)) if start else req_date
                        if effective <= req_date: effective=req_date
                        adj.append((effective, vals[0]))
        return sorted(adj)

    def stream_specs(self, uid, req_date):
        """Infer stable recurring streams from settled history. Future explicit events override projections."""
        groups=defaultdict(list)
        for e in self.by_user[uid]:
            if e.amount is None or e.status != "settled" or e.cash_date > req_date: continue
            groups[(e.event_type,e.category,e.direction,e.flexibility)].append(e)
        specs=[]
        for key, arr in groups.items():
            arr.sort(key=lambda e:e.cash_date)
            if len(arr)<5: continue
            dates=[e.cash_date for e in arr]
            intervals=[(dates[i]-dates[i-1]).days for i in range(1,len(dates))]
            recent=intervals[-5:]
            # Dataset recurrence families: 5, 7, 10, 14, ~30/31 days.
            cadence=int(round(Counter(recent).most_common(1)[0][0]))
            if cadence not in {5,7,10,14,21,28,29,30,31}: continue
            if sum(abs(x-cadence)<=1 for x in recent) < max(3,len(recent)-1): continue
            specs.append({"key":key,"history":arr,"cadence":cadence,"amount":sum(e.amount for e in arr[-5:])/min(5,len(arr[-5:]))})
        return specs

    def forecast_events(self, uid, req_date, changes=None):
        changes = changes or {}
        end=req_date+timedelta(days=90)
        prof=self.profiles[uid]; home=prof["home_currency"]
        actual=[e for e in self.by_user[uid] if e.cash_date>=req_date and e.cash_date<=end and e.status in ACTIVE_STATUSES and e.amount is not None]
        # Deduplicate lifecycle duplicates: if a later settled event references an earlier event, keep the settled event.
        ids=set(); clean=[]
        for e in sorted(actual,key=lambda x:(x.cash_date,x.event_id)):
            if e.linked_event_id and any(a.event_id==e.linked_event_id for a in actual):
                # refund/settlement linked to earlier lifecycle event is still a distinct cash event.
                pass
            clean.append(e)
        by_key=defaultdict(list)
        for e in clean: by_key[(e.event_type,e.category,e.direction,e.flexibility)].append(e)
        projected=[]
        for spec in self.stream_specs(uid, req_date):
            key=spec["key"]; hist=spec["history"]; fut=by_key.get(key,[])
            last=max([e.cash_date for e in hist]+[e.cash_date for e in fut] or [req_date])
            x=last+timedelta(days=spec["cadence"])
            while x<=end:
                # Skip dates already represented by explicit future rows.
                if not any(abs((e.cash_date-x).days)<=1 for e in fut):
                    amt=spec["amount"]
                    if key[1]=="salary":
                        for eff,val in self.parse_message_adjustments(uid,req_date):
                            if x>=eff: amt=val
                    projected.append((x, amt, key[2], key[1], key[3], None, key[0]))
                x+=timedelta(days=spec["cadence"])
        # Explicit future events take precedence over projected values.
        for e in clean:
            amt=e.amount
            if e.currency!=home: amt*=self.fx(e.cash_date,e.currency,home)
            projected.append((e.cash_date,amt,e.direction,e.category,e.flexibility,e.event_id,e.event_type))
        # Apply salary amendment to future scheduled salary records only when the message explicitly changes it.
        for i,row in enumerate(projected):
            d,amt,direction,cat,flex,eid,etype=row
            if cat=="salary" and direction=="credit":
                for eff,val in self.parse_message_adjustments(uid,req_date):
                    if d>=eff: projected[i]=(d,val,direction,cat,flex,eid,etype)
        # Apply optional recurring spending changes.
        for i,row in enumerate(projected):
            d,amt,direction,cat,flex,eid,etype=row
            if direction=="debit" and eid in changes.get("stop",set()): projected[i]=(d,0,direction,cat,flex,eid,etype)
            if direction=="debit" and eid in changes.get("reduce",{}): projected[i]=(d,min(amt,changes["reduce"][eid]),direction,cat,flex,eid,etype)
        projected.sort(key=lambda x:x[0])
        return projected

    def simulate(self, uid, req_date, payments=None, changes=None):
        payments=payments or {}
        prof=self.profiles[uid]; bal=float(prof["current_available_balance"]); minimum=float(prof["minimum_balance_to_keep"])
        rows=self.forecast_events(uid,req_date,changes)
        byday=defaultdict(float)
        for d,amt,direction,*_ in rows: byday[d]+=amt if direction=="credit" else -amt
        minbal=bal
        for i in range(91):
            d=req_date+timedelta(days=i)
            bal += byday.get(d,0.0) - payments.get(d,0.0)
            minbal=min(minbal,bal)
            if bal < minimum-1e-7: return False,minbal,bal
        return True,minbal,bal

    def get_trajectory(self, uid, req_date, payments=None, changes=None):
        payments = payments or {}
        prof = self.profiles[uid]
        bal = float(prof["current_available_balance"])
        minimum = float(prof["minimum_balance_to_keep"])
        rows = self.forecast_events(uid, req_date, changes)
        byday_net = defaultdict(float)
        byday_events = defaultdict(list)
        for d, amt, direction, cat, flex, eid, etype in rows:
            byday_net[d] += amt if direction == "credit" else -amt
            byday_events[d].append({"amount": amt, "direction": direction, "category": cat, "flexibility": flex, "event_id": eid, "event_type": etype})
        trajectory = []
        running = bal
        for i in range(91):
            d = req_date + timedelta(days=i)
            flow = byday_net.get(d, 0.0)
            pmt = payments.get(d, 0.0)
            running += flow - pmt
            trajectory.append({
                "day": i,
                "date": d,
                "balance": round(running, 2),
                "net_flow": round(flow, 2),
                "payment": round(pmt, 2),
                "minimum": minimum,
                "headroom": round(running - minimum, 2),
                "is_breach": running < minimum - 1e-7,
                "events": byday_events.get(d, [])
            })
        return trajectory


    def safe_today(self, uid, req_date):
        prof=self.profiles[uid]; bal=float(prof["current_available_balance"]); minimum=float(prof["minimum_balance_to_keep"])
        ok, minbal, _=self.simulate(uid,req_date,{})
        # Maximum immediate debit that preserves the 90-day floor.
        headroom=max(0.0,bal-minimum)
        if ok:
            # Find the tightest future cushion after the baseline cash flow.
            rows=self.forecast_events(uid,req_date); byday=defaultdict(float)
            for d,a,direction,*_ in rows: byday[d]+=a if direction=="credit" else -a
            running=bal; min_running=running
            for i in range(91):
                d=req_date+timedelta(days=i); running+=byday.get(d,0); min_running=min(min_running,running)
            return max(0.0, min(headroom, min_running-minimum))
        # If baseline itself dips below minimum, safe immediate payment is reduced by the worst deficit.
        return max(0.0, headroom + (minbal-minimum))

    def earliest_full(self, uid, req_date, amount, changes=None, limit=None):
        limit=limit or req_date+timedelta(days=90)
        # Capacity date is independent of method preference. Search each date and test full payment that day.
        d=req_date
        while d<=limit:
            # Forecast from original request date, but add a single payment on d.
            ok,_,_=self.simulate(uid,req_date,{d:amount},changes)
            if ok: return d
            d+=timedelta(days=1)
        return None

    def parse_option(self,o,home):
        n=int(float(o["number_of_payments"])); amt=float(o["payment_amount"]); first=fdate(o["first_payment_date"])
        freq=float(o["payment_frequency_days"]) if (o.get("payment_frequency_days") and str(o["payment_frequency_days"]).strip()) else 0.0
        return [(first+timedelta(days=int(round(i*freq))), amt) for i in range(n)]

    def option_safe(self,uid,req_date,o,changes=None):
        payments=self.parse_option(o,self.profiles[uid]["home_currency"])
        if payments[-1][0] > req_date+timedelta(days=90): return False
        return self.simulate(uid,req_date,{d:a for d,a in payments},changes)[0]

    def evaluate_all_options(self, uid, req_date, request_id, deadline):
        prof = self.profiles[uid]
        home = prof["home_currency"]
        user_methods = set(x for x in prof["payment_methods_user_will_consider"].split('|') if x)
        results = []
        for o in self.options_by_request.get(request_id, []):
            method = o["payment_method"]
            plan = self.parse_option(o, home)
            last_date = plan[-1][0]
            within_horizon = last_date <= req_date + timedelta(days=90)
            within_deadline = last_date <= deadline
            accepted = method in user_methods
            safe, minbal, _ = self.simulate(uid, req_date, {d: a for d, a in plan})
            
            reasons = []
            if not accepted: reasons.append(f"Method '{method}' not in user preferences")
            if not within_deadline: reasons.append(f"Final payment ({last_date}) exceeds user deadline ({deadline})")
            if not within_horizon: reasons.append(f"Final payment ({last_date}) exceeds 90-day horizon")
            if not safe: reasons.append(f"Breaches buffer (dips to {home} {minbal:,.2f})")
            
            results.append({
                "payment_option_id": o["payment_option_id"],
                "payment_method": method,
                "number_of_payments": int(float(o["number_of_payments"])),
                "frequency_days": o.get("payment_frequency_days") or "—",
                "payment_amount": float(o["payment_amount"]),
                "total_payable_amount": float(o["total_payable_amount"]),
                "financing_fee": float(o.get("financing_fee", 0) or 0),
                "first_payment_date": plan[0][0].isoformat(),
                "last_payment_date": last_date.isoformat(),
                "is_safe": safe,
                "is_eligible": safe and within_deadline and within_horizon and accepted,
                "rejection_reasons": reasons,
                "schedule": plan
            })
        return results


    def choose_changes(self,uid,req_date,requested,deadline,safe_today):
        prof=self.profiles[uid]
        reduce_cats=set(x for x in prof["expense_categories_user_is_willing_to_reduce"].split('|') if x)
        stop_cats=set(x for x in prof["expense_categories_user_is_willing_to_stop"].split('|') if x)
        candidates=[]
        # Identify recurring events whose category is user-adjustable.
        for spec in self.stream_specs(uid,req_date):
            et,cat,direction,flex=spec["key"]
            if direction!="debit" or et not in {"expense","subscription"}: continue
            ev=spec["history"][-1];
            if cat in stop_cats and flex in {"stoppable","reducible_or_stoppable"}:
                candidates.append(("stop",ev.event_id,0.0,cat))
            elif cat in reduce_cats and flex in {"reducible","reducible_or_stoppable"} and ev.minimum_allowed_amount is not None:
                candidates.append(("reduce",ev.event_id,ev.minimum_allowed_amount,cat))
        # Greedy by estimated 90-day savings, then event id.
        scored=[]
        for typ,eid,val,cat in candidates:
            if typ=="stop": changes={"stop":{eid},"reduce":{}}
            else: changes={"stop":set(),"reduce":{eid:val}}
            ok=self.simulate(uid,req_date,{req_date:requested},changes)[0]
            if ok: return f"stop:{eid}" if typ=="stop" else f"reduce_to:{eid}:{money(val):g}"
            # score via effect on minimum balance
            base=self.simulate(uid,req_date,{req_date:requested})[1]
            adj=self.simulate(uid,req_date,{req_date:requested},changes)[1]
            scored.append((adj-base,typ,eid,val))
        scored.sort(reverse=True)
        selected=[]; cur={"stop":set(),"reduce":{}}
        for _,typ,eid,val in scored:
            if typ=="stop": cur["stop"].add(eid); selected.append(f"stop:{eid}")
            else: cur["reduce"][eid]=val; selected.append(f"reduce_to:{eid}:{money(val):g}")
            if self.simulate(uid,req_date,{req_date:requested},cur)[0]: return "|".join(selected[:3])
            if len(selected)>=3: break
        return "none"

    def recommend(self,r):
        uid=r["user_id"]; req_date=fdate(r["request_date"]); deadline=fdate(r["desired_completion_date"]); amount=float(r["requested_amount"]); partial_ok=str(r["allows_partial_payment"]).lower()=="true"
        prof=self.profiles[uid]; prefs=set(x for x in prof["payment_methods_user_will_consider"].split('|') if x)
        safe=min(amount,self.safe_today(uid,req_date))
        earliest=self.earliest_full(uid,req_date,amount)
        changes="none"
        # Immediate eligible options, ranked by completion, no changes, lower total, earlier start, fewer payments, id.
        candidates=[]
        if "full_payment" in prefs and safe+1e-7>=amount:
            candidates.append((0,0,amount,req_date,1,"full_payment",[(req_date,amount)],"none"))
        if "partial_payment" in prefs and partial_ok and 0<safe<amount and earliest and earliest<=deadline:
            plan=[(req_date,safe),(earliest,amount-safe)]
            if self.simulate(uid,req_date,{d:a for d,a in plan})[0]:
                candidates.append((0,0,amount,req_date,2,"partial_payment",plan,"none"))
        if "installments" in prefs:
            for o in self.options_by_request[r["request_id"]]:
                if o["payment_method"]!="installments": continue
                n=int(float(o["number_of_payments"])); plan=self.parse_option(o,prof["home_currency"])
                if plan[-1][0]<=deadline and self.option_safe(uid,req_date,o):
                    candidates.append((0,0,float(o["total_payable_amount"]),plan[0][0],n,"installments",plan,"none",o["payment_option_id"]))
        if candidates:
            candidates.sort(key=lambda x:(x[0],x[1],x[2],x[3],x[4],x[-1] if len(x)>8 else ""))
            c=candidates[0]
            method=c[5]; plan=c[6]; change=c[7]
            # full payment may require allowed spending changes if it is just above safe.
            if method=="full_payment" and safe<amount:
                pass
            return self._row(r,safe,"affordable_now" if method=="full_payment" and change=="none" else "affordable_with_plan",method,plan,earliest,change)

        # Try spending changes for full payment first. Changes are only recurring flexible streams.
        if "full_payment" in prefs and safe < amount:
            ch=self.choose_changes(uid,req_date,amount,deadline,safe)
            if ch!="none":
                stop=set(); red={}
                for part in ch.split('|'):
                    bits=part.split(':')
                    if bits[0]=='stop': stop.add(bits[1])
                    else: red[bits[1]]=float(bits[2])
                changes={"stop":stop,"reduce":red}
                if self.simulate(uid,req_date,{req_date:amount},changes)[0]:
                    return self._row(r,safe,"affordable_with_plan","full_payment",[(req_date,amount)],earliest,ch)

        # Wait is allowed only when full payment becomes safe later and the user accepts full payment.
        if "full_payment" in prefs and earliest and earliest<=deadline:
            return self._row(r,safe,"affordable_later","wait",[(earliest,amount)],earliest,"none")
        return self._row(r,safe,"not_affordable","not_recommended",[],earliest,"none")

    def _row(self,r,safe,status,method,plan,earliest,changes):
        uid=r["user_id"]; cur=self.profiles[uid]["home_currency"]; amount=float(r["requested_amount"])
        def fmt(a): return (f"{money(a):.2f}").rstrip("0").rstrip(".")
        plan_s="|".join(f"{d.isoformat()}:{fmt(a)}" for d,a in sorted(plan)) if plan else "none"
        ear=earliest.isoformat() if earliest else ""
        if method=="not_recommended": expl=f"Do not proceed. Only {cur} {fmt(safe)} is safely available today; the full {cur} {fmt(amount)} request cannot be completed within the forecast."
        elif method=="wait": expl=f"Wait and pay {cur} {fmt(amount)} on {earliest.isoformat()}; paying sooner would breach the forecast safety buffer."
        elif changes!="none": expl=f"Pay {cur} {fmt(amount)} on {r['request_date']} and make the listed flexible-spending changes; this keeps the 90-day balance above the minimum."
        elif method=="installments": expl=f"Use the selected installment schedule for the full {cur} {fmt(amount)} request; the forecast remains above the minimum balance."
        elif method=="partial_payment": expl=f"Pay {cur} {fmt(safe)} today and the remaining {cur} {fmt(amount-safe)} on {earliest.isoformat()}; the full request completes safely by the deadline."
        else: expl=f"Pay {cur} {fmt(amount)} today; the 90-day forecast remains above the required minimum balance."
        return {"request_id":r["request_id"],"amount_safe_to_pay":fmt(min(amount,max(0,safe))),"affordability_status":status,"recommended_payment_method":method,"payment_plan":plan_s,"earliest_date_for_full_payment":ear,"spending_changes_needed":changes,"decision_explanation":expl}

    def diagnose(self, r_or_id):
        """Provide detailed end-to-end diagnostic context for a request."""
        if isinstance(r_or_id, str):
            r = next((x for x in self.requests if x["request_id"] == r_or_id), None)
            if not r: raise ValueError(f"Request '{r_or_id}' not found")
        else:
            r = r_or_id
        uid = r["user_id"]
        req_date = fdate(r["request_date"])
        deadline = fdate(r["desired_completion_date"])
        amount = float(r["requested_amount"])
        prof = self.profiles[uid]
        rec = self.recommend(r)
        
        plan_payments = {}
        if rec["payment_plan"] != "none":
            for part in rec["payment_plan"].split('|'):
                d_str, amt_str = part.split(':')
                plan_payments[date.fromisoformat(d_str)] = float(amt_str)
                
        ch = rec["spending_changes_needed"]
        changes_dict = {"stop": set(), "reduce": {}}
        if ch != "none":
            for part in ch.split('|'):
                bits = part.split(':')
                if bits[0] == 'stop':
                    changes_dict["stop"].add(bits[1])
                else:
                    changes_dict["reduce"][bits[1]] = float(bits[2])
                    
        baseline_traj = self.get_trajectory(uid, req_date)
        plan_traj = self.get_trajectory(uid, req_date, payments=plan_payments, changes=changes_dict)
        streams = self.stream_specs(uid, req_date)
        options = self.evaluate_all_options(uid, req_date, r["request_id"], deadline)
        user_messages = [m for m in self.messages if m["user_id"] == uid]
        salary_adjustments = self.parse_message_adjustments(uid, req_date)
        
        return {
            "request": r,
            "profile": prof,
            "recommendation": rec,
            "baseline_trajectory": baseline_traj,
            "plan_trajectory": plan_traj,
            "recurring_streams": streams,
            "payment_options_eval": options,
            "messages": user_messages,
            "salary_adjustments": salary_adjustments,
            "safe_amount_today": float(rec["amount_safe_to_pay"]),
            "requested_amount": amount,
            "home_currency": prof["home_currency"],
            "lowest_balance_baseline": min(t["balance"] for t in baseline_traj),
            "lowest_balance_with_plan": min(t["balance"] for t in plan_traj),
            "minimum_balance_to_keep": float(prof["minimum_balance_to_keep"]),
            "current_available_balance": float(prof["current_available_balance"]),
        }

    def evaluate_custom(self, user_id, amount, req_date=None, deadline=None, category="purchase",
                        allows_partial=True, request_text="Custom expense inquiry",
                        balance_override=None, min_balance_override=None, changes_override=None):
        """Simulate an arbitrary custom financial expense for any user with optional guardrail overrides."""
        if user_id not in self.profiles:
            raise ValueError(f"User {user_id} not found")
        
        req_d = fdate(req_date) if isinstance(req_date, str) else (req_date or date(2025, 1, 1))
        dead_d = fdate(deadline) if isinstance(deadline, str) else (deadline or req_d + timedelta(days=60))
        if dead_d < req_d:
            dead_d = req_d + timedelta(days=30)
            
        orig_prof = dict(self.profiles[user_id])
        try:
            if balance_override is not None:
                self.profiles[user_id]["current_available_balance"] = str(float(balance_override))
            if min_balance_override is not None:
                self.profiles[user_id]["minimum_balance_to_keep"] = str(float(min_balance_override))
            
            custom_r = {
                "request_id": f"custom_{user_id}",
                "user_id": user_id,
                "request_date": req_d.isoformat(),
                "request_type": category,
                "requested_amount": str(float(amount)),
                "desired_completion_date": dead_d.isoformat(),
                "allows_partial_payment": "True" if allows_partial else "False",
                "request_text": request_text
            }
            diag = self.diagnose(custom_r)
            
            if changes_override:
                plan_payments = {}
                if diag["recommendation"]["payment_plan"] != "none":
                    for part in diag["recommendation"]["payment_plan"].split('|'):
                        d_str, amt_str = part.split(':')
                        plan_payments[date.fromisoformat(d_str)] = float(amt_str)
                else:
                    plan_payments = {req_d: float(amount)}
                    
                custom_traj = self.get_trajectory(user_id, req_d, payments=plan_payments, changes=changes_override)
                diag["custom_plan_trajectory"] = custom_traj
                diag["custom_lowest_balance"] = min(t["balance"] for t in custom_traj)
                min_floor = float(self.profiles[user_id]["minimum_balance_to_keep"])
                diag["custom_is_safe"] = all(t["balance"] >= min_floor - 1e-7 for t in custom_traj)
            
            return diag
        finally:
            self.profiles[user_id] = orig_prof

    def run(self, out_path=None):
        out_file = Path(out_path) if out_path else OUT
        rows = [self.recommend(r) for r in self.requests]
        self.validate(rows)
        with open(out_file, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=OUTPUT_COLS)
            w.writeheader()
            w.writerows(rows)
        return rows

    def validate(self,rows):
        assert len(rows)==len(self.requests)
        assert [r["request_id"] for r in rows]==[r["request_id"] for r in self.requests]
        for x in rows:
            req=next(r for r in self.requests if r["request_id"]==x["request_id"])
            a=float(x["amount_safe_to_pay"]); q=float(req["requested_amount"])
            assert 0<=a<=q+1e-8
            assert x["affordability_status"] in VALID_STATUS
            assert x["recommended_payment_method"] in VALID_METHOD
            if x["payment_plan"]!="none":
                dates=[]
                for part in x["payment_plan"].split('|'):
                    d,v=part.split(':'); dates.append(date.fromisoformat(d)); assert float(v)>=0
                assert dates==sorted(dates)
            if x["recommended_payment_method"]=="partial_payment": assert x["affordability_status"]=="affordable_with_plan"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Buy or Wait? AI Financial Affordability Engine")
    parser.add_argument("--request", type=str, help="Inspect diagnostic for a specific request_id (e.g. request_26)")
    parser.add_argument("--stats", action="store_true", help="Print summary statistics across all requests")
    parser.add_argument("--output", type=str, default=str(OUT), help="Output path for predictions CSV")
    args = parser.parse_args()

    engine = Engine()

    if args.request:
        diag = engine.diagnose(args.request)
        req = diag["request"]
        prof = diag["profile"]
        rec = diag["recommendation"]
        cur = diag["home_currency"]
        print(f"\n" + "="*60)
        print(f" REQUEST DIAGNOSTICS: {req['request_id']} (User: {req['user_id']})")
        print("="*60)
        print(f" Question:       \"{req['request_text']}\"")
        print(f" Category:       {req['request_type']} | Date: {req['request_date']} | Deadline: {req['desired_completion_date']}")
        print(f" Requested Amt:  {cur} {float(req['requested_amount']):,.2f}")
        print(f" Available Bal:  {cur} {float(prof['current_available_balance']):,.2f}")
        print(f" Min Required:   {cur} {float(prof['minimum_balance_to_keep']):,.2f}")
        print("-" * 60)
        print(f" Safe Today:     {cur} {diag['safe_amount_today']:,.2f}")
        print(f" Status:         {rec['affordability_status'].upper()}")
        print(f" Recommended:    {rec['recommended_payment_method']}")
        print(f" Payment Plan:   {rec['payment_plan']}")
        print(f" Earliest Full:  {rec['earliest_date_for_full_payment'] or 'None'}")
        print(f" Spending Cut:   {rec['spending_changes_needed']}")
        print(f" Explanation:    {rec['decision_explanation']}")
        print("-" * 60)
        print(f" Lowest Forecast: Baseline={cur} {diag['lowest_balance_baseline']:,.2f} | With Plan={cur} {diag['lowest_balance_with_plan']:,.2f}")
        print(f" Detected Recurring Streams: {len(diag['recurring_streams'])}")
        for s in diag['recurring_streams']:
            print(f"   • {s['key'][1].title()} ({s['key'][0]}, {s['key'][2]}): {cur} {s['amount']:,.2f} every ~{s['cadence']} days")
        if diag['payment_options_eval']:
            print(f" Payment Options Available: {len(diag['payment_options_eval'])}")
            for opt in diag['payment_options_eval']:
                status_str = "SAFE & ELIGIBLE" if opt['is_eligible'] else f"REJECTED: {', '.join(opt['rejection_reasons'])}"
                print(f"   • Option {opt['payment_option_id']} ({opt['payment_method']}, {opt['number_of_payments']} payments): {status_str}")
        print("="*60 + "\n")
    elif args.stats:
        rows = [engine.recommend(r) for r in engine.requests]
        status_counts = Counter(r["affordability_status"] for r in rows)
        method_counts = Counter(r["recommended_payment_method"] for r in rows)
        total = len(rows)
        print("\n" + "="*60)
        print(f" DATASET EVALUATION SUMMARY ({total} requests)")
        print("="*60)
        print(" Affordability Status Breakdown:")
        for s, c in status_counts.most_common():
            print(f"   {s:25s}: {c:3d} ({c/total*100:5.1f}%)")
        print("\n Recommended Payment Methods:")
        for m, c in method_counts.most_common():
            print(f"   {m:25s}: {c:3d} ({c/total*100:5.1f}%)")
        print("="*60 + "\n")
    else:
        rows = engine.run(args.output)
        print(f"Successfully validated and wrote {len(rows)} predictions to {args.output}")

